#!/bin/bash

# Generate a list of all variables in the file that need replacing.
# Variables to be replaced are surrounded by '%' characters, like "%TARGET%".
VARS_TO_REPLACE=`grep '%.*%' $1 | sed -E 's/(^[^%]*%)|(%[^%]*$)//g' | sed 's/%[^%]*%/\n/g' | sort -u`

TARGET_UPPERCASE=$(echo "$TARGET" | tr [a-z] [A-Z])

for var in $VARS_TO_REPLACE
do
    if ! [ "${!var}" ]
    then
        echo "$var is either not set or empty." >&2
        exit 1
    else
        echo "$var = ${!var}" >&2
    fi
done

if ! [ -f "$1" ]
then
    echo "First argument should be a regular file." >&2
    exit 1
fi

for var in $VARS_TO_REPLACE
do
    sed -i "s#%${var}%#${!var}#g" $1 || exit 1
done
